- name: Register system
  debug:
    msg:
      location: "{{ item.0.location }}"
      site: "{{ item.0.site }}"
      rack: "{{ item.0.rack }}"
      name: "{{ item.1.name }}"

  loop: "{{ netbox_servers|subelements('servers') }}"
  loop_control:
    label: "{{ item.1.name }}"

- name: Register NICS
  include_tasks: register_nics.yaml
  loop: "{{ netbox_servers|subelements('servers') }}"
  loop_control:
    label: "{{ item.1.name }}"
