all:
  children:
    servers:
      children:
        ovirt:
          hosts:
            ov1.massopen.cloud:
            ov2.massopen.cloud:
            ov3.massopen.cloud:
            neu-17-40:
              ansible_host: 172.16.17.40
            neu-19-40:
              ansible_host: 172.16.19.40
          vars:
            calculate_rack: true
        cache_servers:
          hosts:
            neu-3-41:
              ansible_host: 10.128.0.25
            neu-5-41:
              ansible_host: 10.128.0.30
            neu-15-41:
              ansible_host: 10.128.0.31
            neu-17-41:
              ansible_host: 10.128.0.59
            neu-19-41:
              ansible_host: 10.128.0.19
          vars:
            calculate_rack: true
            height: 1
        misc:
          hosts:
            neu-3-30:
              ansible_host: 172.16.3.30
              height: 2
              ipmi_ip: 10.0.3.30
            neu-5-30:
              ansible_host: 172.16.5.30
              height: 2
              ipmi_ip: 10.0.5.30
          vars:
            calculate_rack: true
        production_ceph:
          hosts:
            kzn-mon1:
              ansible_host: 172.16.19.14
            kzn-mon2:
              ansible_host: 172.16.17.14
            kzn-mon3:
              ansible_host: 172.16.5.14
            kzn-osd05:
              ansible_host: 172.16.19.15
            kzn-osd06:
              ansible_host: 172.16.17.15
            kzn-osd07:
              ansible_host: 172.16.5.15
            kzn-osd08:
              ansible_host: 172.16.3.15
            kzn-osd09:
              ansible_host: 172.16.19.21
            kzn-osd10:
              ansible_host: 172.16.17.21
            kzn-osd11:
              ansible_host: 172.16.15.14
            kzn-osd12:
              ansible_host: 172.16.15.24
            kzn-osd13:
              ansible_host: 172.16.5.32
            kzn-osd14:
              ansible_host: 172.16.3.32
          vars:
            calculate_rack: true
        openstack_controllers:
          hosts:
            neu-19-11:
              ansible_host: 172.16.19.11
            neu-17-11:
              ansible_host: 172.16.17.11
            neu-15-39:
              ansible_host: 172.16.15.39
            neu-5-39:
              ansible_host: 172.16.5.39
            neu-3-39:
              ansible_host: 172.16.3.39
          vars:
            calculate_rack: true
        openstack_computes:
          hosts:
            neu-3-35:
              ansible_host: 172.16.5.35
            neu-3-37:
              ansible_host: 172.16.3.37
            neu-5-36:
              ansible_host: 172.16.5.36
            neu-5-38:
              ansible_host: 172.16.5.38
            neu-15-34:
              ansible_host: 172.16.15.34
            neu-5-34:
              ansible_host: 172.16.5.34
            neu-15-38:
              ansible_host: 172.16.15.38
            neu-5-35:
              ansible_host: 172.16.5.35
            neu-3-38:
              ansible_host: 172.16.3.38
            neu-3-34:
              ansible_host: 172.16.3.34
            neu-5-37:
              ansible_host: 172.16.5.37
            neu-15-36:
              ansible_host: 172.16.15.36
            neu-15-37:
              ansible_host: 172.16.15.37
            neu-3-36:
              ansible_host: 172.16.3.36
            neu-15-35:
              ansible_host: 172.16.15.35
            neu-15-12:
              ansible_host: 172.16.15.12
            neu-17-2:
              ansible_host: 172.16.17.2
            neu-17-1:
              ansible_host: 172.16.17.1
            neu-19-1:
              ansible_host: 172.16.19.1
            neu-19-3:
              ansible_host: 172.16.19.3
            neu-19-5:
              ansible_host: 172.16.19.5
            neu-17-4:
              ansible_host: 172.16.17.4
            neu-17-3:
              ansible_host: 172.16.17.3
            neu-19-2:
              ansible_host: 172.16.19.2
            neu-19-4:
              ansible_host: 172.16.19.4
            neu-19-12:
              ansible_host: 172.16.19.12
          vars:
            calculate_rack: true
      vars:
        ansible_user: root
        location: Row3/PodB
        calculate_rack: false
    switches:
      children:
        brocade:
          hosts:
            brocade-3-43:
              ansible_host: 10.0.3.43
              calculate_rack: true
            brocade-3-42:
              ansible_host: 10.0.3.42
              calculate_rack: true
            brocade-5-43:
              ansible_host: 10.0.5.43
              calculate_rack: true
            brocade-5-42:
              ansible_host: 10.0.5.42
              calculate_rack: true
            brocade-15-43:
              ansible_host: 10.0.15.43
              calculate_rack: true
            brocade-15-42:
              ansible_host: 10.0.15.42
              calculate_rack: true
            brocade-17-43:
              ansible_host: 10.0.17.43
              calculate_rack: true
            brocade-19-43:
              ansible_host: 10.0.19.43
              calculate_rack: true
            brocade-e1-101:
              ansible_host: 10.10.10.64
              location: Row4/PodA
              rack_number: 2
              rackpos: 41
            brocade-e1-102:
              ansible_host: 10.10.10.65
              location: Row4/PodA
              rack_number: 2
              rackpos: 42
            brocade-e1-103:
              ansible_host: 10.10.10.66
              location: Row4/PodA
              rack_number: 2
              rackpos: 43
            brocade-e1-104:
              ansible_host: 10.10.10.67
              location: Row4/PodA
              rack_number: 4
              rackpos: 43
            brocade-kumo:
              ansible_host: 10.0.21.24
              location: Row4/PodA
              rack_number: 21
              rackpos: 24
          vars:
            ansible_network_os: nos
            ansible_password: "{{ moc_brocade_password }}"
        cisco:
          hosts:
            cisco-19-42:
              ansible_host: 10.0.19.42
              calculate_rack: true
            cisco-17-42:
              ansible_host: 10.0.17.42
              calculate_rack: true
            kumo-nexus:
              ansible_host: 10.1.11.2
              rack_number: 23
              rackpos: 40
              location: Row4/PodA
              ansible_password: "{{ kumo_nexus_password }}"
          vars:
            ansible_password: "{{ moc_cisco_password }}"
            ansible_network_os: cisco.nxos.nxos
        mellanox_onyx:
          hosts:
            bu-21-21:
              ansible_host: 10.0.21.21
            bu-21-23:
              ansible_host: 10.0.21.23
          vars:
            ansible_network_os: onyx
            ansible_become: true
            ansible_become_method: enable
            location: Row4/PodA
            ansible_password: "{{ mellanox_password }}"
            calculate_rack: true
      vars:
        ansible_user: admin
        ansible_connection: ansible.netcommon.network_cli
        calculate_rack: false
        location: Row3/PodB
    ipmi_switches:
      children:
        brocade_icx:
          hosts:
            ipmi-cage3:
              ansible_host: 10.0.3.44
            ipmi-cage5:
              ansible_host: 10.0.5.44
            ipmi-cage15:
              ansible_host: 10.0.15.44
            ipmi-cage17:
              ansible_host: 10.0.17.44
          vars:
            calculate_rack: true
            model: brocade_icx
            manufacturer: Brocade
        ibm:
          hosts:
            ipmi-cage19:
              ansible_host: 10.0.19.44
              calculate_rack: true
          vars:
            model: RackSwitch G8000
            manufacturer: IBM
        cisco_catalyst:
          hosts:
            r4-pA-c23-catalyst3650:
              ansible_host: 10.0.23.41
              calculate_rack: true
            egg1-r4pAc04-mgmt:
              ansible_host: 10.10.10.1
              rack_number: 4
              rackpos: 44
            egg1-r4pAc02-mgmt:
              ansible_host: 10.10.10.2
              rack_number: 2
              rackpos: 44
          vars:
            manufacturer: Cisco
            model: catalyst3650
            location: Row4/PodA
        juniper:
          hosts:
            e1-r4pAc04-mgmt-02:
              ansible_host: 10.10.10.5
              rack_number: 4
              rackpos: 42
              location: Row4/PodA
              manufacturer: Juniper
              model: ex3300
        cumulus:
          hosts:
            bu-21-25:
              ansible_host: 10.0.21.25
              calculate_rack: true
              manufacturer: Accton
              model: as4610_54
              location: Row4/PodA
      vars:
        calculate_rack: false
        location: Row3/PodB
    virtual_machines:
      children:
        ovirt_cluster:
          hosts:
            ansible:
              ansible_host: 172.16.0.204
            ceph-production-public-dhcp:
              ansible_host: 172.16.0.215
            dhcp1.cnv.massopen.cloud:
              ansible_host: 129.10.5.55
            dhcp2.cnv.massopen.cloud:
              ansible_host: 129.10.5.56
            dns.massopen.cloud:
            foreman:
              ansible_host: 172.16.0.3
            freeipa.infra.massopen.cloud:
            freeipa2.infra.massopen.cloud:
            helpdeskvm.massopen.cloud:
            ovirt.massopen.cloud:
            kcephdata:
              ansible_host: 192.168.32.8
            kumo-hil:
              ansible_host: 172.16.100.115
            kumo-hil-client.infra.massopen.cloud:
            kzn-cacti:
              ansible_host: 172.16.0.7
            kzn-dns2:
              ansible_host: 172.16.0.8
            kzn-hil-server.infra.massopen.cloud:
            kzn-ipmi-gw.infra.massopen.cloud:
            kzn-ipmi2-gw.infra.massopen.cloud:
            kzn-nagios.infra.massopen.cloud:
            kzn-ovpn.massopen.cloud:
            kzn-rgw1.infra.massopen.cloud:
            kzn-rgw2.infra.massopen.cloud:
            kzn-rgw-j-01:
              ansible_host: 172.16.0.205
            kzn-rgw-j-02:
              ansible_host: 172.16.0.221
            kzn-rmon1:
              ansible_host: 192.168.32.1
            kzn-rmon2:
              ansible_host: 192.168.32.2
            kzn-rmon3:
              ansible_host: 192.168.32.3
            kzn-rtr.infra.massopen.cloud:
            kzn-ssh.infra.massopen.cloud:
            kzn-undercloud:
              ansible_host: 172.16.0.5
            maas.massopen.cloud:
            mochat.infra.massopen.cloud:
            mondata.infra.massopen.cloud:
            openstack-monitoring:
              ansible_host: 172.16.0.213
            ns1.osh.massopen.cloud:
            ns2.osh.massopen.cloud:
            rcephdata:
              ansible_host: 192.168.32.7
            kzn-recdns1.infra.massopen.cloud:
            kzn-recdns2.infra.massopen.cloud:
            reports.infra.massopen.cloud:
            rhel-6-repomirror:
              ansible_host: 129.10.5.110
            rz.infra.massopen.cloud:
            sso1.infra.massopen.cloud:
            sso2.infra.massopen.cloud:
            stackgraf:
              ansible_host: 192.168.32.11
            tld.massopen.cloud:
            ns2.massopen.cloud:
            www.massopen.cloud:
            zabbix.massopen.cloud:
          vars:
            cluster: "ovirt_cluster"
        neu_3_30_cluster:
          hosts:
            kaizenbm.massopen.cloud:
          vars:
            cluster: "neu_3_30_cluster"
      vars:
        ansible_user: root
